import type { Category, Product } from "@/lib/types"

export const CATALOG_SEED_CATEGORIES: Category[] = [
  {
    id: "premium-masala",
    name: "Premium Masala",
    slug: "premium-masala",
    enabled: true,
  },
  {
    id: "combo-pack-masala",
    name: "Combo Pack Masala",
    slug: "combo-pack-masala",
    enabled: true,
  },
  {
    id: "raw-organic-spices",
    name: "Raw Organic Spices",
    slug: "raw-organic-spices",
    enabled: false,
  },
]

export const CATALOG_SEED_PRODUCTS: Product[] = [
  {
    id: "garam-masala-premium",
    name: "Mix Masala Premium Blend",
    category: "premium-masala",
    price: 210,
    packGrams: 50,
    image: "images/products/garam-masala-premium.png",
    rating: 4.8,
    reviewCount: 5,
    description:
      "Our flagship, rich, and highly aromatic blend crafted with rare and expensive spices like Stone Flower, Long Pepper, and Mace. No added salt or fillers.",
    ingredients: [
      "Cumin (Jeera)",
      "Caraway Seeds (Shahi Jeera)",
      "Black Cardamom (Badi Elaichi)",
      "Coriander (Dhaniya)",
      "Black Pepper (Kali Mirch)",
      "White Pepper (Safed Mirch)",
      "Cloves (Laung)",
      "Green Cardamom (Choti Elaichi)",
      "Mace (Javitri)",
      "Turmeric (Haldi)",
      "Poppy Seeds (Khas Khas)",
      "Dried Fenugreek Leaves (Kasuri Methi)",
      "Cinnamon (Dalchini)",
      "Nutmeg (Jaiphal)",
      "Long Pepper (Pipali)",
      "Star Anise (Chakra Phool)",
      "Stone Flower (Patthar Phool)",
      "Bay Leaf (Tej Patta)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["bestseller", "premium", "aromatic"],
  },
  {
    id: "bharwa-masala-premium",
    name: "Bharwa Masala",
    category: "premium-masala",
    price: 125,
    packGrams: 50,
    image: "images/products/bharwa-masala-premium.png",
    rating: 4.7,
    reviewCount: 4,
    description:
      "A fragrant, coarsely ground blend dominated by roasted cumin and fennel. Designed specifically to bring out the best in stuffed karela, bhindi, or baingan.",
    ingredients: [
      "Cumin (Jeera)",
      "Fennel (Saunf)",
      "Coriander (Dhaniya)",
      "Dry Mango Powder (Amchoor)",
      "Red Chilli (Lal Mirch)",
      "Edible Common Salt",
      "Turmeric (Haldi)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["premium", "stuffed-veggies", "tangy"],
  },
  {
    id: "chat-masala-premium",
    name: "Chaat Masala",
    category: "premium-masala",
    price: 145,
    packGrams: 50,
    image: "images/products/chat-masala-premium.png",
    rating: 4.9,
    reviewCount: 3,
    description:
      "A highly addictive, lip-smacking blend that balances tartness with a spicy kick. Perfect for sprinkling on fruits, salads, and street-style snacks.",
    ingredients: [
      "Cumin (Jeera)",
      "Dry Mango Powder (Amchoor)",
      "Coriander (Dhaniya)",
      "Black Salt (Kala Namak)",
      "Edible Common Salt",
      "Black Pepper (Kali Mirch)",
      "White Pepper (Safed Mirch)",
      "Red Chilli (Lal Mirch)",
      "Dry Ginger (Sonth)",
      "Tartaric Acid (Tatri)",
      "Sugar",
      "Dried Gooseberry (Amla)",
      "Carom Seeds (Ajwain)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["bestseller", "premium", "tangy", "street-food"],
  },
  {
    id: "chhole-masala-premium",
    name: "Chole Masala",
    category: "premium-masala",
    price: 160,
    packGrams: 50,
    image: "images/products/chhole-masala-premium.png",
    rating: 4.8,
    reviewCount: 6,
    description:
      "A perfectly balanced, dark, and tangy blend featuring premium Bedgi chillies and Anardana for that authentic Punjabi Chole flavor.",
    ingredients: [
      "Coriander (Dhaniya)",
      "Cumin (Jeera)",
      "Dry Mango Powder (Amchoor)",
      "Fennel (Saunf)",
      "Pomegranate Seeds (Anardana)",
      "Black Pepper (Kali Mirch)",
      "Bedgi Red Chilli",
      "Black Cardamom (Badi Elaichi)",
      "Cinnamon (Dalchini)",
      "Green Cardamom (Choti Elaichi)",
      "Cloves (Laung)",
      "Dry Ginger (Sonth)",
      "Black Salt (Kala Namak)",
      "Rock Salt (Sendha Namak)",
      "Bay Leaf (Tej Patta)",
      "Carom Seeds (Ajwain)",
      "Turmeric (Haldi)",
      "White Pepper (Safed Mirch)",
      "Dried Fenugreek Leaves (Kasuri Methi)",
      "Mace (Javitri)",
      "Caraway Seeds (Shahi Jeera)",
      "Kachri",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["premium", "punjabi", "aromatic"],
  },
  {
    id: "sukhdevi-combo-pack",
    name: "Sukhdevi Combo Pack",
    category: "combo-pack-masala",
    price: 640,
    packGrams: 200,
    image: "images/products/SDA-Combo-Pack.jpeg",
    rating: 5,
    reviewCount: 0,
    description:
      "All four signature 50g masalas in one order: Bharwa Masala, Chaat Masala, Chole Masala, and Mix Masala Premium Blend. Free shipping applies automatically because the combo subtotal is above 500 INR.",
    ingredients: [
      "1 x Bharwa Masala 50g",
      "1 x Chaat Masala 50g",
      "1 x Chole Masala 50g",
      "1 x Mix Masala Premium Blend 50g",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["combo-pack", "free-shipping", "giftable"],
  },
]
