import type { Category, Product } from "@/lib/types"

const DEFAULT_BRAND_NAME = "SukhDevi Alchemy Spices"
const DEFAULT_GTIN = "29EAGPS2390M1ZX"
const DEFAULT_FSSAI = "21226010003872"

const CATEGORY_LABELS: Record<string, string> = {
  "premium-masala": "Premium Blended Masala",
  "tea-masala": "Tea Masala",
  "combo-pack-masala": "Combo Pack Masala",
  "raw-organic-spices": "Raw Organic Spices",
}

export const CATALOG_SEED_CATEGORIES: Category[] = [
  {
    id: "premium-masala",
    name: "Premium Blended Masala",
    slug: "premium-masala",
    enabled: true,
  },
  {
    id: "tea-masala",
    name: "Tea Masala",
    slug: "tea-masala",
    enabled: true,
  },
  {
    id: "combo-pack-masala",
    name: "Combo Pack Masala",
    slug: "combo-pack-masala",
    enabled: true,
  },
  {
    id: "raw-organic-spices",
    name: "Raw Organic Spices",
    slug: "raw-organic-spices",
    enabled: true,
  },
]

const BASE_CATALOG_SEED_PRODUCTS: Product[] = [
  {
    id: "garam-masala-premium",
    name: "Premium Masala Spice Blend",
    sku: "SDK06260001",
    amazonUrl: "https://www.amazon.in/dp/B0H6MQP2HT",
    category: "premium-masala",
    price: 160,
    compareAtPrice: 320,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/419FQ-lBADL._SY300_SX300_QL70_ML2_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description:
      "Our flagship, rich, and highly aromatic blend crafted with rare and expensive spices like Stone Flower, Long Pepper, and Mace. No added salt or fillers.",
    ingredients: [
      "Cumin (Jeera)",
      "Caraway Seeds (Shahi Jeera)",
      "Black Cardamom (Badi Elaichi)",
      "Coriander (Dhaniya)",
      "Black Pepper (Kali Mirch)",
      "White Pepper (Safed Mirch)",
      "Cloves (Laung)",
      "Green Cardamom (Choti Elaichi)",
      "Mace (Javitri)",
      "Turmeric (Haldi)",
      "Poppy Seeds (Khas Khas)",
      "Dried Fenugreek Leaves (Kasuri Methi)",
      "Cinnamon (Dalchini)",
      "Nutmeg (Jaiphal)",
      "Long Pepper (Pipali)",
      "Star Anise (Chakra Phool)",
      "Stone Flower (Patthar Phool)",
      "Bay Leaf (Tej Patta)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    highlights: [
      "Amazon ASIN: B0H6MQP2HT",
      "Amazon status: Active (last changed 25 Jun 2026)",
      "Amazon buy box: 160.00 + 80.00 shipping",
      "Amazon available inventory: 100 (FBM)",
      "Amazon total fees: 1.18",
    ],
    tags: ["bestseller", "premium", "aromatic"],
    modelNumber: "SDA-GM-70",
  },
  {
    id: "bharwa-masala-premium",
    name: "Bharwa Masala",
    sku: "0F-6SL4-PQ3O",
    amazonUrl: "https://www.amazon.in/dp/B0H8CR4LMC",
    category: "premium-masala",
    price: 55,
    compareAtPrice: 135,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71m3+3eZaJL._SY550_.jpg",
    rating: 4.7,
    reviewCount: 0,
    description:
      "A fragrant, coarsely ground blend dominated by roasted cumin and fennel. Designed specifically to bring out the best in stuffed karela, bhindi, or baingan.",
    ingredients: [
      "Cumin (Jeera)",
      "Fennel (Saunf)",
      "Coriander (Dhaniya)",
      "Dry Mango Powder (Amchoor)",
      "Red Chilli (Lal Mirch)",
      "Edible Common Salt",
      "Turmeric (Haldi)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    highlights: [
      "Amazon ASIN: B0H8CR4LMC",
      "Amazon status: Active (last changed 10 Jul 2026)",
      "Amazon buy box: 55.00 + 80.00 shipping",
      "Amazon available inventory: 100 (FBM)",
      "Amazon total fees: 1.18",
    ],
    tags: ["premium", "stuffed-veggies", "tangy"],
    modelNumber: "SDA-BM-70",
  },
  {
    id: "chat-masala-premium",
    name: "Chat Masala",
    sku: "GY-DI7F-WW2L",
    amazonUrl: "https://www.amazon.in/dp/B0H8CP8NTG",
    category: "premium-masala",
    price: 75,
    compareAtPrice: 150,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71WhsD02NQL._SY550_.jpg",
    rating: 4.9,
    reviewCount: 0,
    description:
      "A highly addictive, lip-smacking blend that balances tartness with a spicy kick. Perfect for sprinkling on fruits, salads, and street-style snacks.",
    ingredients: [
      "Cumin (Jeera)",
      "Dry Mango Powder (Amchoor)",
      "Coriander (Dhaniya)",
      "Black Salt (Kala Namak)",
      "Edible Common Salt",
      "Black Pepper (Kali Mirch)",
      "White Pepper (Safed Mirch)",
      "Red Chilli (Lal Mirch)",
      "Dry Ginger (Sonth)",
      "Tartaric Acid (Tatri)",
      "Sugar",
      "Dried Gooseberry (Amla)",
      "Carom Seeds (Ajwain)",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    highlights: [
      "Amazon ASIN: B0H8CP8NTG",
      "Amazon status: Active (last changed 10 Jul 2026)",
      "Amazon buy box: 75.00 + 80.00 shipping",
      "Amazon available inventory: 100 (FBM)",
      "Amazon total fees: 1.18",
    ],
    tags: ["bestseller", "premium", "tangy", "street-food"],
    modelNumber: "SDA-CM-70",
  },
  {
    id: "chhole-masala-premium",
    name: "Chhole Masala",
    sku: "65-NBPN-U4BC",
    amazonUrl: "https://www.amazon.in/dp/B0H8CKHSY4",
    category: "premium-masala",
    price: 85,
    compareAtPrice: 170,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71gonnuiigL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description:
      "A perfectly balanced, dark, and tangy blend featuring premium Bedgi chillies and Anardana for that authentic Punjabi Chole flavor.",
    ingredients: [
      "Coriander (Dhaniya)",
      "Cumin (Jeera)",
      "Dry Mango Powder (Amchoor)",
      "Fennel (Saunf)",
      "Pomegranate Seeds (Anardana)",
      "Black Pepper (Kali Mirch)",
      "Bedgi Red Chilli",
      "Black Cardamom (Badi Elaichi)",
      "Cinnamon (Dalchini)",
      "Green Cardamom (Choti Elaichi)",
      "Cloves (Laung)",
      "Dry Ginger (Sonth)",
      "Black Salt (Kala Namak)",
      "Rock Salt (Sendha Namak)",
      "Bay Leaf (Tej Patta)",
      "Carom Seeds (Ajwain)",
      "Turmeric (Haldi)",
      "White Pepper (Safed Mirch)",
      "Dried Fenugreek Leaves (Kasuri Methi)",
      "Mace (Javitri)",
      "Caraway Seeds (Shahi Jeera)",
      "Kachri",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    highlights: [
      "Amazon ASIN: B0H8CKHSY4",
      "Amazon status: Active (last changed 10 Jul 2026)",
      "Amazon buy box: 85.00 + 80.00 shipping",
      "Amazon available inventory: 100 (FBM)",
      "Amazon total fees: 1.18",
    ],
    tags: ["premium", "punjabi", "aromatic"],
    modelNumber: "SDA-CHM-70",
  },
  {
    id: "garam-masala-crest",
    name: "Garam Masala Crest",
    sku: "SDA07260002",
    amazonUrl: "https://www.amazon.in/dp/B0H883XH3L",
    category: "premium-masala",
    price: 105,
    compareAtPrice: 200,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/719GEhJH7IL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description:
      "A bold and aromatic premium garam masala blend crafted for rich curries, dals, and everyday Indian cooking.",
    ingredients: [
      "Coriander",
      "Cumin",
      "Dry red chilli",
      "Somp",
      "Black pepper",
      "Cassia",
      "Bay Leaves",
      "Cloves",
      "Black Cardamom",
      "Star anise",
      "Ginger",
      "Shahi jeera",
      "Salt",
      "Green cardamom",
      "Mace",
      "Nutmeg",
    ],
    inStock: true,
    highlights: [
      "Amazon ASIN: B0H883XH3L",
      "Amazon status: Active (last changed 9 Jul 2026)",
      "Amazon buy box: 105.00 + 80.00 shipping",
      "Amazon available inventory: 100 (FBM)",
      "Amazon total fees: 1.18",
    ],
    tags: ["premium", "aromatic"],
    modelNumber: "SDA-GMC-70",
  },
  {
    id: "ginger-tea-masala",
    name: "Ginger Tea Masala",
    sku: "P0-89NE-LGV5",
    amazonUrl: "https://www.amazon.in/dp/B0H8CVJWMZ",
    category: "tea-masala",
    price: 125,
    compareAtPrice: 220,
    packGrams: 50,
    image: "https://m.media-amazon.com/images/I/71mSOaIKpVL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Hand-roasted tea masala blend with ginger-forward warmth for everyday chai.",
    ingredients: ["Ginger", "Licorice", "Cardamom", "Clove", "Black Pepper"],
    inStock: true,
    tags: ["tea-masala", "amazon-live"],
    modelNumber: "P0-89NE-LGV5",
  },
  {
    id: "elaichi-tea-masala",
    name: "Elaichi Tea Masala",
    sku: "SX-KWBY-CLQ3",
    amazonUrl: "https://www.amazon.in/dp/B0H8CLZ5TQ",
    category: "tea-masala",
    price: 230,
    compareAtPrice: 360,
    packGrams: 50,
    image: "https://m.media-amazon.com/images/I/711S5TseR9L._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Cardamom-forward chai masala blend with clove, ginger, and licorice notes.",
    ingredients: ["Cloves", "Cardamom", "Black Pepper", "Long Pepper", "Dried Ginger", "Licorice"],
    inStock: true,
    tags: ["tea-masala", "amazon-live"],
    modelNumber: "SX-KWBY-CLQ3",
  },
  {
    id: "dal-chini-cinnamon-tea-masala",
    name: "Dal-Chini Cinnamon Tea Masala",
    sku: "WW-E8W9-Z01T",
    amazonUrl: "https://www.amazon.in/dp/B0H8CPD5XB",
    category: "tea-masala",
    price: 100,
    compareAtPrice: 260,
    packGrams: 50,
    image: "https://m.media-amazon.com/images/I/71skjLsCs-L._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Cinnamon-led tea masala for a warm, aromatic, spiced chai cup.",
    ingredients: ["Cinnamon", "Licorice", "Cardamom", "Cloves", "Black Pepper", "Nutmeg"],
    inStock: true,
    tags: ["tea-masala", "amazon-live"],
    modelNumber: "WW-E8W9-Z01T",
  },
  {
    id: "pav-bhaji-masala",
    name: "Pav Bhaji Masala",
    sku: "9N-JF7B-0JTS",
    amazonUrl: "https://www.amazon.in/dp/B0H8CJ4BL9",
    category: "premium-masala",
    price: 80,
    compareAtPrice: 180,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71SaayNd2zL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Street-style pav bhaji masala with aromatic whole spices and tangy depth.",
    ingredients: ["Coriander", "Red Chilli", "Cumin", "Mango", "Fennel", "Black Salt", "Salt", "Black Pepper", "Cassia", "Bay Leaf", "Cloves", "Ginger", "Turmeric", "Black Cardamom", "Cardamom", "Star Anise", "Nutmeg", "Mace", "Stone Flower", "Dried Fenugreek Leaves"],
    inStock: true,
    tags: ["premium", "amazon-live"],
    modelNumber: "9N-JF7B-0JTS",
  },
  {
    id: "rajma-masala",
    name: "Rajma Masala",
    sku: "7R-4DX9-H8LU",
    amazonUrl: "https://www.amazon.in/dp/B0H88LDZNM",
    category: "premium-masala",
    price: 75,
    compareAtPrice: 160,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71A3Mi6D0DL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Rich rajma masala blend with tangy, warm, and earthy spice notes.",
    ingredients: ["Coriander", "Cumin", "Kashmiri Red Chilli", "Dry Mango", "Pomegranate Seeds", "Tamarind", "Mint", "Dried Fenugreek Leaves", "Green Cardamom", "Black Cardamom", "Cloves", "Nutmeg", "Mace", "Stone Flower", "Caraway", "Fennel"],
    inStock: true,
    tags: ["premium", "amazon-live"],
    modelNumber: "7R-4DX9-H8LU",
  },
  {
    id: "garam-masala-koppa",
    name: "Garam Masala Koppa",
    sku: "SDA07260003",
    amazonUrl: "https://www.amazon.in/dp/B0H88HWY2Z",
    category: "premium-masala",
    price: 115,
    compareAtPrice: 200,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/711dvCdO7TL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Hand-roasted garam masala blend with coriander, cumin, and warming spices.",
    ingredients: ["Coriander", "Cumin", "Black Pepper", "Ginger", "Cassia", "Yellow Chilli", "Black Cardamom", "Cloves", "Nutmeg", "Mace", "Caraway", "Kasuri Methi"],
    inStock: true,
    tags: ["premium", "amazon-live"],
    modelNumber: "SDA07260003",
  },
  {
    id: "sambhar-masala",
    name: "Sambhar Masala",
    sku: "N6-QOIC-YO7U",
    amazonUrl: "https://www.amazon.in/dp/B0H884FS8X",
    category: "premium-masala",
    price: 65,
    compareAtPrice: 150,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/717iehYzyQL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Traditional South Indian sambhar masala with roasted lentils and whole spices.",
    ingredients: ["Coriander", "Red Chilli", "Cumin", "Chana Dal", "Urad Dal", "Toor Dal", "Fenugreek Seeds", "Raw Rice", "Curry Leaves", "Tamarind", "Turmeric", "Dalchini", "Hing", "Rayi", "Salt", "Black Pepper"],
    inStock: true,
    tags: ["premium", "amazon-live"],
    modelNumber: "N6-QOIC-YO7U",
  },
  {
    id: "peri-peri-masala",
    name: "Peri-Peri Masala",
    sku: "SKA07260001",
    amazonUrl: "https://www.amazon.in/dp/B0H87Q9YRD",
    category: "premium-masala",
    price: 80,
    compareAtPrice: 170,
    packGrams: 70,
    image: "https://m.media-amazon.com/images/I/71bXc46FZtL._SY550_.jpg",
    rating: 4.8,
    reviewCount: 0,
    description: "Bold peri-peri masala with red chilli, garlic, herbs, and citrusy tang.",
    ingredients: ["Red Chilli", "Garlic", "Onion", "Oregano", "Parsley", "Sugar", "Salt", "Dry Mango Powder", "Black Pepper", "Thyme", "Lemon Powder", "Cumin"],
    inStock: true,
    tags: ["premium", "amazon-live"],
    modelNumber: "SKA07260001",
  },
  {
    id: "sukhdevi-combo-pack",
    name: "Sukhdevi Combo Pack",
    category: "combo-pack-masala",
    price: 640,
    packGrams: 200,
    image: "images/products/SDA-Combo-Pack.jpeg",
    rating: 5,
    reviewCount: 0,
    description:
      "All four signature 50g masalas in one order: Bharwa Masala, Chaat Masala, Chole Masala, and Mix Masala Premium Blend. Free shipping applies automatically because the combo subtotal is above 500 INR.",
    ingredients: [
      "1 x Bharwa Masala 50g",
      "1 x Chaat Masala 50g",
      "1 x Chole Masala 50g",
      "1 x Mix Masala Premium Blend 50g",
    ],
    youtubeUrl: "https://youtu.be/pDOFN9OEKt4?si=RyDFBeFCk1LY0ZHi",
    inStock: true,
    tags: ["combo-pack", "free-shipping", "giftable"],
    modelNumber: "SDA-COMBO-200",
  },
  {
    id: "raw-cardamom-black",
    name: "Raw Black Cardamom",
    category: "raw-organic-spices",
    price: 140,
    packGrams: 50,
    image: "images/products/Raw-Cardamom-Black-8inch.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Bold and smoky black cardamom pods sourced for authentic Indian gravies and biryanis.",
    ingredients: ["Black Cardamom (Badi Elaichi)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-cardamom-green",
    name: "Raw Green Cardamom",
    category: "raw-organic-spices",
    price: 260,
    packGrams: 50,
    image: "images/products/Raw-Cardamom-Green-8inch.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Premium aromatic green cardamom for desserts, tea, and spice blends.",
    ingredients: ["Green Cardamom (Choti Elaichi)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-clove",
    name: "Raw Clove",
    category: "raw-organic-spices",
    price: 90,
    packGrams: 50,
    image: "images/products/Raw-Clove.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Strong and fragrant cloves ideal for tempering, pulao, and masala chai.",
    ingredients: ["Cloves (Laung)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-cumin",
    name: "Raw Cumin",
    category: "raw-organic-spices",
    price: 50,
    packGrams: 50,
    image: "images/products/Raw-Cumin.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Clean and earthy cumin seeds for daily tadka and roasting blends.",
    ingredients: ["Cumin (Jeera)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-fennel-lucknow",
    name: "Raw Fennel",
    category: "raw-organic-spices",
    price: 25,
    packGrams: 50,
    image: "images/products/Raw-Fennel-Lucknow.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Sweet Lucknow fennel with bright aroma for curries, pickles, and mouth fresheners.",
    ingredients: ["Fennel (Saunf)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-guntur-chilli",
    name: "Raw Cuntur Chilli",
    category: "raw-organic-spices",
    price: 25,
    packGrams: 50,
    image: "images/products/Raw-Guntur-Chilli.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Classic Guntur red chilli for vibrant color and medium heat in Indian dishes.",
    ingredients: ["Guntur Red Chilli"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-pepper-black",
    name: "Raw Black Pepper",
    category: "raw-organic-spices",
    price: 80,
    packGrams: 50,
    image: "images/products/Raw-Pepper-Black.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Sharp and woody black peppercorns suitable for seasoning and fresh grinding.",
    ingredients: ["Black Pepper (Kali Mirch)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-star-anise",
    name: "Raw Star Anise",
    category: "raw-organic-spices",
    price: 80,
    packGrams: 50,
    image: "images/products/Raw-Star-Anise.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Licorice-forward star anise pods for biryani, broths, and slow-cooked gravies.",
    ingredients: ["Star Anise (Chakra Phool)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-tej-patta",
    name: "Raw Tej Patta",
    category: "raw-organic-spices",
    price: 40,
    packGrams: 50,
    image: "images/products/Raw-Tej-Patta.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Aromatic bay leaves to deepen flavor in dals, rice, and gravies.",
    ingredients: ["Bay Leaf (Tej Patta)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
  {
    id: "raw-turmeric",
    name: "Raw Turmeric",
    category: "raw-organic-spices",
    price: 35,
    packGrams: 50,
    image: "images/products/Raw-Turmeric.JPG",
    rating: 5,
    reviewCount: 0,
    description: "Natural turmeric fingers for grinding fresh haldi powder and immunity blends.",
    ingredients: ["Turmeric (Haldi)"],
    inStock: true,
    tags: ["raw", "organic", "whole-spice"],
  },
]

function toSlug(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

function inferShortDescription(description: string) {
  const firstSentence = description.split(".")[0]?.trim()
  if (firstSentence) {
    return `${firstSentence}.`
  }

  return description
}

function inferHighlights(product: Product) {
  const packGrams = product.packGrams ?? 50
  const isRawSpice = product.category === "raw-organic-spices"

  if (isRawSpice) {
    return [
      "Single-ingredient whole spice",
      `Net quantity: ${packGrams}g`,
      "Packed for freshness and daily kitchen use",
    ]
  }

  return [
    "Crafted in small batches for consistent aroma",
    `Net quantity: ${packGrams}g`,
    "Ingredient panel is clearly declared on this page",
  ]
}

function inferMaterialInfo(product: Product) {
  if (product.category === "raw-organic-spices") {
    return "Whole spice"
  }

  if (product.category === "combo-pack-masala") {
    return "Combo pack of blended spice pouches"
  }

  return "Ground spice blend"
}

function inferModelNumber(product: Product) {
  if (product.modelNumber?.trim()) {
    return product.modelNumber.trim()
  }

  return `SDA-${product.id.toUpperCase().replace(/[^A-Z0-9]+/g, "-")}`
}

function inferBreadcrumb(product: Product) {
  const categoryName = CATEGORY_LABELS[product.category] ?? product.category
  return ["Home", "Products", categoryName, product.name]
}

export const CATALOG_SEED_PRODUCTS: Product[] = BASE_CATALOG_SEED_PRODUCTS.map((product) => {
  const packGrams = product.packGrams ?? 50

  return {
    ...product,
    slug: toSlug(product.id),
    brandName: product.brandName ?? DEFAULT_BRAND_NAME,
    shortDescription: product.shortDescription ?? inferShortDescription(product.description),
    highlights: product.highlights && product.highlights.length > 0 ? product.highlights : inferHighlights(product),
    modelNumber: inferModelNumber(product),
    mpn: product.mpn ?? product.sku,
    gtin: product.gtin ?? DEFAULT_GTIN,
    variantData: product.variantData && product.variantData.length > 0
      ? product.variantData
      : [`Pack Size: ${packGrams}g`],
    netQuantityValue: product.netQuantityValue ?? packGrams,
    netQuantityUnit: product.netQuantityUnit ?? "g",
    materialInfo: product.materialInfo ?? inferMaterialInfo(product),
    complianceInfo: product.complianceInfo && product.complianceInfo.length > 0
      ? product.complianceInfo
      : [
          `FSSAI Lic. No.: ${DEFAULT_FSSAI}`,
          `GTIN/GSTIN: ${DEFAULT_GTIN}`,
          "Store in a cool and dry place",
          "Keep away from moisture and direct sunlight",
          "Review ingredient and allergen suitability before consumption",
        ],
    additionalImages: product.additionalImages ?? [],
    categoryBreadcrumb: product.categoryBreadcrumb && product.categoryBreadcrumb.length > 0
      ? product.categoryBreadcrumb
      : inferBreadcrumb(product),
  }
})
