-- Seed Raw Organic Spices products and ensure category is enabled for existing environments.

update public.categories
set enabled = true
where id = 'raw-organic-spices';

insert into public.products (
  id,
  category_id,
  sku,
  name,
  description,
  price_per_100g,
  image_path,
  rating_avg,
  review_count,
  ingredients,
  tags,
  youtube_url,
  in_stock,
  is_active
)
values
  (
    'raw-cardamom-black',
    'raw-organic-spices',
    'RO-BLK-CARDAMOM-001',
    'Raw Black Cardamom',
    'Bold and smoky black cardamom pods sourced for authentic Indian gravies and biryanis.',
    135,
    'images/products/Raw-Cardamom-Black-8inch.JPG',
    5,
    0,
    array['Black Cardamom (Badi Elaichi)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-cardamom-green',
    'raw-organic-spices',
    'RO-GRN-CARDAMOM-001',
    'Raw Green Cardamom',
    'Premium aromatic green cardamom for desserts, tea, and spice blends.',
    255,
    'images/products/Raw-Cardamom-Green-8inch.JPG',
    5,
    0,
    array['Green Cardamom (Choti Elaichi)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-clove',
    'raw-organic-spices',
    'RO-CLOVE-001',
    'Raw Clove',
    'Strong and fragrant cloves ideal for tempering, pulao, and masala chai.',
    90,
    'images/products/Raw-Clove.JPG',
    5,
    0,
    array['Cloves (Laung)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-cumin',
    'raw-organic-spices',
    'RO-CUMIN-001',
    'Raw Cumin',
    'Clean and earthy cumin seeds for daily tadka and roasting blends.',
    52,
    'images/products/Raw-Cumin.JPG',
    5,
    0,
    array['Cumin (Jeera)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-fennel-lucknow',
    'raw-organic-spices',
    'RO-FENNEL-001',
    'Raw Fennel Lucknow',
    'Sweet Lucknow fennel with bright aroma for curries, pickles, and mouth fresheners.',
    26,
    'images/products/Raw-Fennel-Lucknow.JPG',
    5,
    0,
    array['Fennel (Saunf)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-guntur-chilli',
    'raw-organic-spices',
    'RO-GUNTUR-001',
    'Raw Guntur Chilli',
    'Classic Guntur red chilli for vibrant color and medium heat in Indian dishes.',
    23,
    'images/products/Raw-Guntur-Chilli.JPG',
    5,
    0,
    array['Guntur Red Chilli'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-pepper-black',
    'raw-organic-spices',
    'RO-BLK-PEPPER-001',
    'Raw Black Pepper',
    'Sharp and woody black peppercorns suitable for seasoning and fresh grinding.',
    78,
    'images/products/Raw-Pepper-Black.JPG',
    5,
    0,
    array['Black Pepper (Kali Mirch)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-star-anise',
    'raw-organic-spices',
    'RO-STAR-ANISE-001',
    'Raw Star Anise',
    'Licorice-forward star anise pods for biryani, broths, and slow-cooked gravies.',
    78,
    'images/products/Raw-Star-Anise.JPG',
    5,
    0,
    array['Star Anise (Chakra Phool)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-tej-patta',
    'raw-organic-spices',
    'RO-TEJ-PATTA-001',
    'Raw Tej Patta',
    'Aromatic bay leaves to deepen flavor in dals, rice, and gravies.',
    38,
    'images/products/Raw-Tej-Patta.JPG',
    5,
    0,
    array['Bay Leaf (Tej Patta)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  ),
  (
    'raw-turmeric',
    'raw-organic-spices',
    'RO-TURMERIC-001',
    'Raw Turmeric',
    'Natural turmeric fingers for grinding fresh haldi powder and immunity blends.',
    33,
    'images/products/Raw-Turmeric.JPG',
    5,
    0,
    array['Turmeric (Haldi)'],
    array['raw','organic','whole-spice'],
    null,
    true,
    true
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  sku = excluded.sku,
  name = excluded.name,
  description = excluded.description,
  price_per_100g = excluded.price_per_100g,
  image_path = excluded.image_path,
  rating_avg = excluded.rating_avg,
  review_count = excluded.review_count,
  ingredients = excluded.ingredients,
  tags = excluded.tags,
  youtube_url = excluded.youtube_url,
  in_stock = excluded.in_stock,
  is_active = excluded.is_active,
  updated_at = now();
