-- Sync Amazon-listed Sukhdevi masala catalog into public.products.
-- Run this after 034_add_amazon_listing_fields.sql and 035_backfill_amazon_listing_defaults.sql.

begin;

insert into public.categories (id, name, slug, enabled, sort_order)
values
  ('premium-masala', 'Premium Blended Masala', 'premium-masala', true, 10),
  ('tea-masala', 'Tea Masala', 'tea-masala', true, 20)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order;

insert into public.products (
  id,
  category_id,
  public_slug,
  sku,
  name,
  short_description,
  description,
  price_per_100g,
  image_path,
  ingredients,
  tags,
  in_stock,
  is_active,
  brand_name,
  bullet_highlights,
  model_number,
  mpn,
  gtin,
  variant_data,
  net_quantity_value,
  net_quantity_unit,
  material_info,
  compliance_info,
  additional_image_paths,
  category_breadcrumb
)
values
  (
    'ginger-tea-masala',
    'tea-masala',
    'ginger-tea-masala',
    'P0-89NE-LGV5',
    'Ginger Tea Masala',
    'Hand-roasted ginger-forward tea masala blend in a 50g glass jar.',
    'Sukhdevi Alchemy Ginger Tea Masala, 50g.',
    125,
    'https://m.media-amazon.com/images/I/71mSOaIKpVL._SY550_.jpg',
    array['Ginger', 'Licorice', 'Cardamom', 'Clove', 'Black Pepper'],
    array['tea-masala', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CVJWMZ', 'Price: INR 125', 'Pack Size: 50g'],
    'P0-89NE-LGV5',
    'P0-89NE-LGV5',
    '29EAGPS2390M1ZX',
    array['Pack Size: 50g'],
    50,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CVJWMZ'],
    array['Home', 'Products', 'Tea Masala', 'Ginger Tea Masala']
  ),
  (
    'elaichi-tea-masala',
    'tea-masala',
    'elaichi-tea-masala',
    'SX-KWBY-CLQ3',
    'Elaichi Tea Masala',
    'Cardamom and clove dominant tea masala in a 50g glass jar.',
    'Sukhdevi Alchemy Elaichi Tea Masala, 50g.',
    230,
    'https://m.media-amazon.com/images/I/711S5TseR9L._SY550_.jpg',
    array['Cloves', 'Cardamom', 'Black Pepper', 'Long Pepper', 'Dried Ginger', 'Licorice'],
    array['tea-masala', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CLZ5TQ', 'Price: INR 230', 'Pack Size: 50g'],
    'SX-KWBY-CLQ3',
    'SX-KWBY-CLQ3',
    '29EAGPS2390M1ZX',
    array['Pack Size: 50g'],
    50,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CLZ5TQ'],
    array['Home', 'Products', 'Tea Masala', 'Elaichi Tea Masala']
  ),
  (
    'dal-chini-cinnamon-tea-masala',
    'tea-masala',
    'dal-chini-cinnamon-tea-masala',
    'WW-E8W9-Z01T',
    'Dal-Chini Cinnamon Tea Masala',
    'Cinnamon-rich tea masala blend in a 50g glass jar.',
    'Sukhdevi Alchemy Dal-Chini Cinnamon Tea Masala, 50g.',
    100,
    'https://m.media-amazon.com/images/I/71skjLsCs-L._SY550_.jpg',
    array['Cinnamon', 'Licorice', 'Cardamom', 'Cloves', 'Black Pepper', 'Nutmeg'],
    array['tea-masala', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CPD5XB', 'Price: INR 100', 'Pack Size: 50g'],
    'WW-E8W9-Z01T',
    'WW-E8W9-Z01T',
    '29EAGPS2390M1ZX',
    array['Pack Size: 50g'],
    50,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CPD5XB'],
    array['Home', 'Products', 'Tea Masala', 'Dal-Chini Cinnamon Tea Masala']
  ),
  (
    'chat-masala-premium',
    'premium-masala',
    'chat-masala',
    'GY-DI7F-WW2L',
    'Chat Masala',
    'Tangy and spicy chat masala blend for fruits and snacks.',
    'Sukhdevi Alchemy Chat Masala, 70g.',
    75,
    'https://m.media-amazon.com/images/I/71WhsD02NQL._SY550_.jpg',
    array['Coriander', 'White Pepper', 'Salt', 'Dry Mango Powder', 'Black Salt', 'Red Chilli', 'Black Pepper', 'Carom Seeds', 'Indian Gooseberry', 'Sugar'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CP8NTG', 'Price: INR 75', 'Pack Size: 70g'],
    'GY-DI7F-WW2L',
    'GY-DI7F-WW2L',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CP8NTG'],
    array['Home', 'Products', 'Premium Blended Masala', 'Chat Masala']
  ),
  (
    'bharwa-masala-premium',
    'premium-masala',
    'bharwa-masala',
    '0F-6SL4-PQ3O',
    'Bharwa Masala',
    'Balanced stuffing masala blend with cumin, fennel, and coriander.',
    'Sukhdevi Alchemy Bharwa Masala, 70g.',
    55,
    'https://m.media-amazon.com/images/I/71m3+3eZaJL._SY550_.jpg',
    array['Cumin', 'Fennel', 'Coriander', 'Dry Mango Powder', 'Red Chilli', 'Edible Common Salt', 'Turmeric'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CR4LMC', 'Price: INR 55', 'Pack Size: 70g'],
    '0F-6SL4-PQ3O',
    '0F-6SL4-PQ3O',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CR4LMC'],
    array['Home', 'Products', 'Premium Blended Masala', 'Bharwa Masala']
  ),
  (
    'pav-bhaji-masala',
    'premium-masala',
    'pav-bhaji-masala',
    '9N-JF7B-0JTS',
    'Pav Bhaji Masala',
    'Mumbai-style pav bhaji masala with layered whole-spice aroma.',
    'Sukhdevi Alchemy Pav Bhaji Masala, 70g.',
    80,
    'https://m.media-amazon.com/images/I/71SaayNd2zL._SY550_.jpg',
    array['Coriander', 'Red Chilli', 'Cumin', 'Mango', 'Fennel', 'Black Salt', 'Salt', 'Black Pepper', 'Cassia', 'Bay Leaf', 'Cloves', 'Ginger', 'Turmeric', 'Black Cardamom', 'Cardamom', 'Star Anise', 'Nutmeg', 'Mace', 'Stone Flower', 'Dried Fenugreek Leaves'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CJ4BL9', 'Price: INR 80', 'Pack Size: 70g'],
    '9N-JF7B-0JTS',
    '9N-JF7B-0JTS',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CJ4BL9'],
    array['Home', 'Products', 'Premium Blended Masala', 'Pav Bhaji Masala']
  ),
  (
    'chhole-masala-premium',
    'premium-masala',
    'chhole-masala',
    '65-NBPN-U4BC',
    'Chhole Masala',
    'Punjabi chhole masala with over 20 spices for deep flavor.',
    'Sukhdevi Alchemy Chhole Masala, 70g.',
    85,
    'https://m.media-amazon.com/images/I/71gonnuiigL._SY550_.jpg',
    array['Coriander', 'Cumin', 'Black Pepper', 'Fennel', 'Clove', 'Black Cardamom', 'Green Cardamom', 'Cinnamon', 'Bay Leaf', 'Carom Seeds', 'Red Chilli', 'Dry Mango Powder', 'Dry Ginger Powder', 'Turmeric', 'Fenugreek', 'Mace', 'Nutmeg', 'Dried Pomegranate Seeds', 'Asafoetida'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H8CKHSY4', 'Price: INR 85', 'Pack Size: 70g'],
    '65-NBPN-U4BC',
    '65-NBPN-U4BC',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H8CKHSY4'],
    array['Home', 'Products', 'Premium Blended Masala', 'Chhole Masala']
  ),
  (
    'rajma-masala',
    'premium-masala',
    'rajma-masala',
    '7R-4DX9-H8LU',
    'Rajma Masala',
    'Rajma masala blend with tangy, warm, and aromatic notes.',
    'Sukhdevi Alchemy Rajma Masala, 70g.',
    75,
    'https://m.media-amazon.com/images/I/71A3Mi6D0DL._SY550_.jpg',
    array['Coriander', 'Cumin', 'Kashmiri Red Chilli', 'Dry Mango', 'Pomegranate Seeds', 'Tamarind', 'Mint', 'Dried Fenugreek Leaves', 'Green Cardamom', 'Black Cardamom', 'Cloves', 'Nutmeg', 'Mace', 'Stone Flower', 'Caraway', 'Fennel'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H88LDZNM', 'Price: INR 75', 'Pack Size: 70g'],
    '7R-4DX9-H8LU',
    '7R-4DX9-H8LU',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H88LDZNM'],
    array['Home', 'Products', 'Premium Blended Masala', 'Rajma Masala']
  ),
  (
    'garam-masala-koppa',
    'premium-masala',
    'garam-masala-koppa',
    'SDA07260003',
    'Garam Masala Koppa',
    'Hand-roasted garam masala with coriander, cumin, and whole-spice warmth.',
    'Sukhdevi Alchemy Garam Masala Koppa, 70g.',
    115,
    'https://m.media-amazon.com/images/I/711dvCdO7TL._SY550_.jpg',
    array['Coriander', 'Cumin', 'Black Pepper', 'Ginger', 'Cassia', 'Yellow Chilli', 'Black Cardamom', 'Cloves', 'Nutmeg', 'Mace', 'Caraway', 'Kasuri Methi'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H88HWY2Z', 'Price: INR 115', 'Pack Size: 70g'],
    'SDA07260003',
    'SDA07260003',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H88HWY2Z'],
    array['Home', 'Products', 'Premium Blended Masala', 'Garam Masala Koppa']
  ),
  (
    'sambhar-masala',
    'premium-masala',
    'sambhar-masala',
    'N6-QOIC-YO7U',
    'Sambhar Masala',
    'South Indian sambhar masala with lentil-roasted spice profile.',
    'Sukhdevi Alchemy Sambhar Masala, 70g.',
    65,
    'https://m.media-amazon.com/images/I/717iehYzyQL._SY550_.jpg',
    array['Coriander', 'Red Chilli', 'Cumin', 'Chana Dal', 'Urad Dal', 'Toor Dal', 'Fenugreek Seeds', 'Raw Rice', 'Curry Leaves', 'Tamarind', 'Turmeric', 'Dalchini', 'Hing', 'Rayi', 'Salt', 'Black Pepper'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H884FS8X', 'Price: INR 65', 'Pack Size: 70g'],
    'N6-QOIC-YO7U',
    'N6-QOIC-YO7U',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H884FS8X'],
    array['Home', 'Products', 'Premium Blended Masala', 'Sambhar Masala']
  ),
  (
    'garam-masala-crest',
    'premium-masala',
    'garam-masala-crest',
    'SDA07260002',
    'Garam Masala Crest',
    'A robust garam masala blend in a 70g glass jar.',
    'Sukhdevi Alchemy Garam Masala Crest, 70g.',
    105,
    'https://m.media-amazon.com/images/I/719GEhJH7IL._SY550_.jpg',
    array['Coriander', 'Cumin', 'Dry Red Chilli', 'Black Pepper', 'Cassia', 'Bay Leaves', 'Cloves', 'Black Cardamom', 'Star Anise', 'Ginger', 'Shahi Jeera', 'Green Cardamom', 'Mace', 'Nutmeg'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H883XH3L', 'Price: INR 105', 'Pack Size: 70g'],
    'SDA07260002',
    'SDA07260002',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H883XH3L'],
    array['Home', 'Products', 'Premium Blended Masala', 'Garam Masala Crest']
  ),
  (
    'peri-peri-masala',
    'premium-masala',
    'peri-peri-masala',
    'SKA07260001',
    'Peri-Peri Masala',
    'Hot and tangy peri-peri spice blend with herbs and citrus notes.',
    'Sukhdevi Alchemy Peri-Peri Masala, 70g.',
    80,
    'https://m.media-amazon.com/images/I/71bXc46FZtL._SY550_.jpg',
    array['Red Chilli', 'Garlic', 'Onion', 'Oregano', 'Parsley', 'Sugar', 'Salt', 'Dry Mango Powder', 'Black Pepper', 'Thyme', 'Lemon Powder', 'Cumin'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H87Q9YRD', 'Price: INR 80', 'Pack Size: 70g'],
    'SKA07260001',
    'SKA07260001',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H87Q9YRD'],
    array['Home', 'Products', 'Premium Blended Masala', 'Peri-Peri Masala']
  ),
  (
    'garam-masala-premium',
    'premium-masala',
    'premium-masala-spice-blend',
    'SDK06260001',
    'Premium Masala Spice Blend',
    'Flagship premium masala blend with layered whole-spice aroma.',
    'Sukhdevi Alchemy Premium Masala Spice Blend, 70g.',
    160,
    'images/products/garam-masala-premium.png',
    array['Cumin', 'Caraway', 'Black Pepper', 'White Pepper', 'Black Cardamom', 'Green Cardamom', 'Nutmeg', 'Mace', 'Stone Flower', 'Turmeric', 'Poppy', 'Dried Fenugreek Leaves', 'Cinnamon', 'Cloves', 'Coriander', 'Long Pepper', 'Anise'],
    array['premium', 'amazon-synced'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['ASIN: B0H6MQP2HT', 'Price: INR 160', 'Pack Size: 70g'],
    'SDK06260001',
    'SDK06260001',
    '29EAGPS2390M1ZX',
    array['Pack Size: 70g'],
    70,
    'g',
    'Ground spice blend',
    array['Store in a cool and dry place'],
    array['https://www.amazon.in/dp/B0H6MQP2HT'],
    array['Home', 'Products', 'Premium Blended Masala', 'Premium Masala Spice Blend']
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  public_slug = excluded.public_slug,
  sku = excluded.sku,
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  price_per_100g = excluded.price_per_100g,
  image_path = excluded.image_path,
  ingredients = excluded.ingredients,
  tags = excluded.tags,
  in_stock = excluded.in_stock,
  is_active = excluded.is_active,
  brand_name = excluded.brand_name,
  bullet_highlights = excluded.bullet_highlights,
  model_number = excluded.model_number,
  mpn = excluded.mpn,
  gtin = excluded.gtin,
  variant_data = excluded.variant_data,
  net_quantity_value = excluded.net_quantity_value,
  net_quantity_unit = excluded.net_quantity_unit,
  material_info = excluded.material_info,
  compliance_info = excluded.compliance_info,
  additional_image_paths = excluded.additional_image_paths,
  category_breadcrumb = excluded.category_breadcrumb,
  updated_at = now();

commit;
