-- Add Cloud Kitchen category and smoothie products.

begin;

insert into public.categories (id, name, slug, enabled, sort_order)
values
  ('cloud-kitchen', 'Cloud Kitchen', 'cloud-kitchen', true, 25)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order;

insert into public.products (
  id,
  category_id,
  public_slug,
  sku,
  name,
  short_description,
  description,
  price_per_100g,
  image_path,
  ingredients,
  tags,
  in_stock,
  is_active,
  brand_name,
  bullet_highlights,
  model_number,
  mpn,
  gtin,
  variant_data,
  net_quantity_value,
  net_quantity_unit,
  material_info,
  compliance_info,
  additional_image_paths,
  category_breadcrumb
)
values
  (
    'apple-smoothie-cloud-kitchen',
    'cloud-kitchen',
    'apple-smoothie',
    'SDA-CK-APPLE-230',
    'Apple Smoothie',
    'Fresh apple smoothie, made to order in a 230ml serving.',
    'Cloud Kitchen Apple Smoothie with optional nuts and seeds add-ons.',
    180,
    'https://images.unsplash.com/photo-1514995669114-6081e934b693?auto=format&fit=crop&w=900&q=80',
    array['Apple', 'Milk/Water Base'],
    array['cloud-kitchen', 'smoothie', 'fresh-made'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['Serving: 230ml', 'Instant delivery charge: INR 30 in 560068', 'Subscription delivery: Free with weekly prepay'],
    'SDA-CK-APPLE-230',
    'SDA-CK-APPLE-230',
    '29EAGPS2390M1ZX',
    array['Serving: 230ml'],
    230,
    'ml',
    'Fresh beverage',
    array['Made fresh after order confirmation', 'Best consumed immediately'],
    array[]::text[],
    array['Home', 'Cloud Kitchen', 'Smoothies', 'Apple Smoothie']
  ),
  (
    'banana-smoothie-cloud-kitchen',
    'cloud-kitchen',
    'banana-smoothie',
    'SDA-CK-BANANA-230',
    'Banana Smoothie',
    'Fresh banana smoothie, made to order in a 230ml serving.',
    'Cloud Kitchen Banana Smoothie with optional nuts and seeds add-ons.',
    150,
    'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?auto=format&fit=crop&w=900&q=80',
    array['Banana', 'Milk/Water Base'],
    array['cloud-kitchen', 'smoothie', 'fresh-made'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['Serving: 230ml', 'Instant delivery charge: INR 30 in 560068', 'Subscription delivery: Free with weekly prepay'],
    'SDA-CK-BANANA-230',
    'SDA-CK-BANANA-230',
    '29EAGPS2390M1ZX',
    array['Serving: 230ml'],
    230,
    'ml',
    'Fresh beverage',
    array['Made fresh after order confirmation', 'Best consumed immediately'],
    array[]::text[],
    array['Home', 'Cloud Kitchen', 'Smoothies', 'Banana Smoothie']
  ),
  (
    'blueberry-smoothie-cloud-kitchen',
    'cloud-kitchen',
    'blueberry-smoothie',
    'SDA-CK-BLUEBERRY-230',
    'Blueberry Smoothie',
    'Fresh blueberry smoothie, made to order in a 230ml serving.',
    'Cloud Kitchen Blueberry Smoothie with optional nuts and seeds add-ons.',
    210,
    'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80',
    array['Blueberry', 'Milk/Water Base'],
    array['cloud-kitchen', 'smoothie', 'fresh-made'],
    true,
    true,
    'Sukhdevi Alchemy',
    array['Serving: 230ml', 'Instant delivery charge: INR 30 in 560068', 'Subscription delivery: Free with weekly prepay'],
    'SDA-CK-BLUEBERRY-230',
    'SDA-CK-BLUEBERRY-230',
    '29EAGPS2390M1ZX',
    array['Serving: 230ml'],
    230,
    'ml',
    'Fresh beverage',
    array['Made fresh after order confirmation', 'Best consumed immediately'],
    array[]::text[],
    array['Home', 'Cloud Kitchen', 'Smoothies', 'Blueberry Smoothie']
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  public_slug = excluded.public_slug,
  sku = excluded.sku,
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  price_per_100g = excluded.price_per_100g,
  image_path = excluded.image_path,
  ingredients = excluded.ingredients,
  tags = excluded.tags,
  in_stock = excluded.in_stock,
  is_active = excluded.is_active,
  brand_name = excluded.brand_name,
  bullet_highlights = excluded.bullet_highlights,
  model_number = excluded.model_number,
  mpn = excluded.mpn,
  gtin = excluded.gtin,
  variant_data = excluded.variant_data,
  net_quantity_value = excluded.net_quantity_value,
  net_quantity_unit = excluded.net_quantity_unit,
  material_info = excluded.material_info,
  compliance_info = excluded.compliance_info,
  additional_image_paths = excluded.additional_image_paths,
  category_breadcrumb = excluded.category_breadcrumb;

commit;
