-- Additive V2 commerce normalization schema.
-- Safe to apply before application cutover. Does not remove legacy order JSON fields.

create extension if not exists pgcrypto;

alter table public.orders
  add column if not exists subtotal_amount numeric(12,2),
  add column if not exists shipping_amount numeric(10,2),
  add column if not exists discount_amount numeric(10,2),
  add column if not exists promo_code text,
  add column if not exists billing_currency text not null default 'INR',
  add column if not exists final_amount_paise bigint,
  add column if not exists pricing_model_version integer not null default 1;

create table if not exists public.product_prices (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  quantity_basis text not null check (quantity_basis in ('per_100g', 'pack')),
  quantity_value integer not null check (quantity_value > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  currency text not null default 'INR',
  version integer not null check (version > 0),
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (product_id, version)
);

create index if not exists product_prices_product_id_idx on public.product_prices(product_id);
create index if not exists product_prices_active_idx on public.product_prices(product_id, valid_from desc);

create table if not exists public.product_discounts (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  discount_type text not null check (discount_type in ('permanent', 'seasonal', 'flash_sale')),
  active_from timestamptz not null default now(),
  expires_at timestamptz,
  version integer not null check (version > 0),
  reason text not null default 'No reason provided',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, version),
  check (
    (discount_type = 'permanent' and expires_at is null)
    or (discount_type in ('seasonal', 'flash_sale') and expires_at is not null and expires_at > active_from)
  )
);

create index if not exists product_discounts_product_id_idx on public.product_discounts(product_id);
create index if not exists product_discounts_active_idx on public.product_discounts(product_id, active_from desc);

drop trigger if exists product_discounts_touch_updated_at on public.product_discounts;
create trigger product_discounts_touch_updated_at
before update on public.product_discounts
for each row
execute function public.touch_updated_at();

create or replace function public.get_current_product_discount(target_product_id text)
returns table (
  id bigint,
  discount_percent numeric,
  discount_type text,
  expires_at timestamptz,
  version integer
)
language sql
stable
set search_path = public
as $$
  select
    pd.id,
    pd.discount_percent,
    pd.discount_type,
    pd.expires_at,
    pd.version
  from public.product_discounts pd
  where pd.product_id = target_product_id
    and pd.active_from <= now()
    and (pd.expires_at is null or pd.expires_at > now())
  order by pd.version desc
  limit 1;
$$;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  product_sku text,
  product_name text not null,
  pack_grams integer not null check (pack_grams > 0),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  line_subtotal numeric(12,2) not null check (line_subtotal >= 0),
  discount_amount numeric(10,2) not null default 0 check (discount_amount >= 0),
  discount_percent numeric(5,2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  discount_type text,
  discount_version_id bigint,
  shipping_allocated_amount numeric(10,2) not null default 0 check (shipping_allocated_amount >= 0),
  tax_percent numeric(5,2) not null default 0 check (tax_percent >= 0 and tax_percent <= 100),
  tax_amount numeric(10,2) not null default 0 check (tax_amount >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  price_version_id bigint,
  price_version_number integer,
  legacy_item_ordinal integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_product_id_idx on public.order_items(product_id);
create index if not exists order_items_created_at_idx on public.order_items(created_at desc);
create unique index if not exists order_items_legacy_item_ordinal_idx on public.order_items(order_id, legacy_item_ordinal);

alter table public.order_items
  add constraint order_items_discount_version_fk
  foreign key (discount_version_id)
  references public.product_discounts(id)
  on delete set null;

alter table public.order_items
  add constraint order_items_price_version_fk
  foreign key (price_version_id)
  references public.product_prices(id)
  on delete set null;

drop trigger if exists order_items_touch_updated_at on public.order_items;
create trigger order_items_touch_updated_at
before update on public.order_items
for each row
execute function public.touch_updated_at();

create table if not exists public.billing_payments (
  id uuid primary key default gen_random_uuid(),
  order_id text references public.orders(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  amount bigint not null check (amount >= 0),
  currency text not null default 'INR',
  razorpay_order_id text,
  razorpay_payment_id text not null,
  status text not null default 'created' check (status in ('created', 'paid', 'failed', 'refunded')),
  line_items_reconciled boolean not null default false,
  reconciled_at timestamptz,
  refund_id uuid,
  raw jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (razorpay_payment_id)
);

alter table public.billing_payments
  add column if not exists order_id text,
  add column if not exists user_id uuid,
  add column if not exists amount bigint,
  add column if not exists currency text,
  add column if not exists razorpay_order_id text,
  add column if not exists razorpay_payment_id text,
  add column if not exists status text,
  add column if not exists line_items_reconciled boolean,
  add column if not exists reconciled_at timestamptz,
  add column if not exists refund_id uuid,
  add column if not exists raw jsonb,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

update public.billing_payments
set
  currency = coalesce(nullif(currency, ''), 'INR'),
  status = coalesce(nullif(status, ''), 'created'),
  line_items_reconciled = coalesce(line_items_reconciled, false),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now())
where
  currency is null
  or status is null
  or line_items_reconciled is null
  or created_at is null
  or updated_at is null;

create index if not exists billing_payments_order_id_idx on public.billing_payments(order_id);
create index if not exists billing_payments_user_id_idx on public.billing_payments(user_id);
create index if not exists billing_payments_razorpay_order_id_idx on public.billing_payments(razorpay_order_id);

alter table public.billing_payments enable row level security;

revoke all on table public.billing_payments from anon;
revoke all on table public.billing_payments from authenticated;
grant select on table public.billing_payments to authenticated;
grant all on table public.billing_payments to service_role;

drop policy if exists "billing_payments_owner_or_admin_select" on public.billing_payments;
create policy "billing_payments_owner_or_admin_select"
on public.billing_payments
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "billing_payments_service_all" on public.billing_payments;
create policy "billing_payments_service_all"
on public.billing_payments
for all
to service_role
using (true)
with check (true);

drop trigger if exists billing_payments_touch_updated_at on public.billing_payments;
create trigger billing_payments_touch_updated_at
before update on public.billing_payments
for each row
execute function public.touch_updated_at();

create table if not exists public.access_entitlements (
  user_id uuid not null references auth.users(id) on delete cascade,
  entitlement_key text not null,
  granted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, entitlement_key)
);

alter table public.access_entitlements enable row level security;

revoke all on table public.access_entitlements from anon;
revoke all on table public.access_entitlements from authenticated;
grant select on table public.access_entitlements to authenticated;
grant all on table public.access_entitlements to service_role;

drop policy if exists "access_entitlements_owner_or_admin_select" on public.access_entitlements;
create policy "access_entitlements_owner_or_admin_select"
on public.access_entitlements
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "access_entitlements_service_all" on public.access_entitlements;
create policy "access_entitlements_service_all"
on public.access_entitlements
for all
to service_role
using (true)
with check (true);

drop trigger if exists access_entitlements_touch_updated_at on public.access_entitlements;
create trigger access_entitlements_touch_updated_at
before update on public.access_entitlements
for each row
execute function public.touch_updated_at();

create table if not exists public.order_refunds (
  id uuid primary key default gen_random_uuid(),
  order_id text not null references public.orders(id) on delete cascade,
  refund_reason text not null,
  refund_status text not null check (refund_status in ('requested', 'approved', 'processing', 'completed', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_refunds_order_id_idx on public.order_refunds(order_id);

drop trigger if exists order_refunds_touch_updated_at on public.order_refunds;
create trigger order_refunds_touch_updated_at
before update on public.order_refunds
for each row
execute function public.touch_updated_at();

create table if not exists public.order_refund_items (
  id bigint generated by default as identity primary key,
  refund_id uuid not null references public.order_refunds(id) on delete cascade,
  order_item_id bigint not null references public.order_items(id) on delete restrict,
  quantity_returned integer not null check (quantity_returned > 0),
  grams_returned integer not null check (grams_returned > 0),
  refund_amount numeric(12,2) not null check (refund_amount >= 0),
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists order_refund_items_refund_id_idx on public.order_refund_items(refund_id);
create index if not exists order_refund_items_order_item_id_idx on public.order_refund_items(order_item_id);

comment on table public.product_prices is 'Historical product pricing snapshots for V2 billing and analytics.';
comment on table public.product_discounts is 'Historical product discounts with permanent and temporary validity windows.';
comment on function public.get_current_product_discount(text) is 'Returns the currently active product discount, preferring the latest valid version.';
comment on table public.order_items is 'Normalized order line items preserving pack, price, and discount snapshot values.';
comment on table public.billing_payments is 'Gateway payment records used for reconciliation and admin reporting.';
comment on table public.access_entitlements is 'Purchased-access entitlements granted after successful payments.';
comment on table public.order_refunds is 'Return or refund requests attached to an order.';
comment on table public.order_refund_items is 'Line-level refund records for partial returns.';
